DROP TABLE IF EXISTS feedback;

DROP TABLE IF EXISTS wishlist_book;
DROP TABLE IF EXISTS wishlist;

DROP TABLE IF EXISTS payments;
DROP TABLE IF EXISTS order_details;
DROP TABLE IF EXISTS orders;

DROP TABLE IF EXISTS cart_details;
DROP TABLE IF EXISTS cart;

DROP TABLE IF EXISTS customers;
DROP TABLE IF EXISTS stock;
DROP TABLE IF EXISTS genres;
DROP TABLE IF EXISTS books_by_authors;
DROP TABLE IF EXISTS authors;
DROP TABLE IF EXISTS books;

DROP TABLE IF EXISTS user_roles;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS users;

